AllCops:
  # remove if using newer cops!
  NewCops: disable
  # remove if using `rubocop-rails`
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/resources/**/*
    - node_modules/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/factories/**/*

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
